<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Formulário/</span> Cadastro de Usuários</h4>

    <!-- Basic Layout -->
    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Dados do Usuário</h5>
                    <small class="text-danger float-end">Todos os campos são obrigatórios *</small>
                </div>
                <div class="card-body">
                    <form method="post" action="/storeusers" enctype="multipart/form-data">
                        <div class="mb-3">
                            <label class="form-label" for="basic-default-fullname">Nome Completo *</label>
                            <input type="text" class="form-control" id="basic-default-fullname" name="fullname" />
                        </div>
                        <div class="mb-3">
                            <label for="largeSelect" class="form-label">Perfil *</label>
                            <select id="largeSelect" class="form-select" name="profile_id">
                                <option class="text-muted" selected>Selecione</option>
                                <?php foreach($this->view->dados as $indice => $profile) { ?>
                                <option value="<?= $profile['id'] ?>"><?= $profile['profileName'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="basic-default-email">Email *</label>
                            <div class="input-group input-group-merge">
                                <input type="text" id="basic-default-email" class="form-control" name="email" />
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="basic-default-password">Senha *</label>
                            <div class="input-group input-group-merge">
                                <input type="password" id="basic-default-password" class="form-control" name="senha" />
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="basic-default-message">Foto de Perfil *</label>
                            <input class="form-control" type="file" name="photo" />
                        </div>

                        <button type="submit" class="btn btn-success">Salvar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
