<!-- Content wrapper -->
<div class="content-wrapper">
  <!-- Content -->
  <div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Formulário/</span> Configurações de Conta</h4>

    <div class="row">
      <div class="col-md-12">
        <div class="card mb-4">
          <h5 class="card-header">Dados do Usuário</h5>
          <!-- Account -->
          <form id="formAccountSettings" method="POST" action="/updateuser?id=<?= $this->view->dados['id'] ?>" enctype="multipart/form-data">
            <div class="card-body">
              <div class="d-flex align-items-start align-items-sm-center gap-4">
                <img src="storage/users/<?= $this->view->dados['photo'] ?>" alt="user-avatar" class="d-block rounded" height="100" width="100" id="uploadedAvatar" />
                <div class="button-wrapper">
                  <label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
                    <span class="d-none d-sm-block">Atualizar Foto</span>
                    <i class="bx bx-upload d-block d-sm-none"></i>
                    <input type="file" id="upload" class="account-file-input" name="photo" hidden  />
                  </label>
                  <p class="text-muted mb-0">Permitido apenas formatos JPG, GIF ou PNG.</p>
                </div>
              </div>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="mb-3 col-md-6">
                  <label for="fullname" class="form-label">Nome Completo</label>
                  <input class="form-control" type="text" id="fullname" name="fullname" value="<?= $this->view->dados['fullname'] ?>" autofocus />
                </div>
                <div class="mb-3 col-md-6">
                  <label for="email" class="form-label">E-mail</label>
                  <input class="form-control" type="text" id="email" name="email" placeholder="email@dominio.com" value="<?= $this->view->dados['email'] ?>" placeholder="john.doe@example.com" />
                </div>
                <div class="mb-3 col-md-6">
                  <label for="largeSelect" class="form-label">Perfil</label>
                  <select id="largeSelect" class="form-select form-select-lg" name="profile_id">
                    <option value="1">Administrador</option>
                  </select>
                </div>
              </div>
              <div class="mt-2">
                <button type="submit" class="btn btn-primary me-2">Salvar Alterações</button>
                <button type="reset" class="btn btn-outline-secondary">Cancelar</button>
              </div>
            </div>
          </form>
          <!-- /Account -->
        </div>
      </div>
    </div>
  </div>
  <!-- / Content -->
  <div class="content-backdrop fade"></div>
</div>
<!-- Content wrapper -->