<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Formulário /</span> Cadastro de Perfil</h4>

    <form action="/storeprofile" method="POST">
        <div class="row">
            <div class="col-md-8">
                <div class="card mb-3">
                    <h5 class="card-header">Criação de Perfis</h5>
                    <div class="card-body">
                        <div class="mb-3">
                            <label for="defaultFormControlInput" class="form-label">Nome do peril</label>
                            <input type="text" class="form-control" name="profileName" id="defaultFormControlInput" placeholder="Administrador" aria-describedby="defaultFormControlHelp" />
                        </div>
                        <button type="submit" class="btn btn-success">Salvar</button>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <div class="row gy-3">
                        <div class="col-md">
                            <h3 class="fw-semibold">Permissões</h3>
                            <div class="form-check mt-3">
                                <input class="form-check-input" type="checkbox" value="1" id="defaultCheck1" />
                                <label class="form-check-label" for="defaultCheck1"> Vizualização </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="2" id="defaultCheck2" />
                                <label class="form-check-label" for="defaultCheck2"> Cadastrar </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="3" id="defaultCheck3" />
                                <label class="form-check-label" for="defaultCheck3"> Atualizar </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="4" id="disabledCheck1" />
                                <label class="form-check-label" for="disabledCheck1"> Deletar </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>